/* Treści przykładowe — zmień je na informacje z własnego świata RP. */
const divisions = {
    osobowe: { label: '01 / MOTORYZACJA', title: 'Samochody osobowe', slogan: 'Każda podróż zaczyna się od dobrego projektu.', heading: 'Technika bliżej kierowcy.', intro: 'Dział motoryzacyjny AsperGenerator projektuje samochody z myślą o codziennym użytkowaniu. Łączymy wyrazistą sylwetkę, przewidywalne prowadzenie i komfort, który docenisz również po długiej trasie.', stats: [['Miejski', 'Kompaktowe proporcje'], ['Touring', 'Komfort na trasie'], ['Sport', 'Precyzja prowadzenia']], second: 'Jeden kierowca. Własna droga.', body: 'Nasza gama obejmuje samochody miejskie, pojazdy klasy biznesowej i warianty sportowe. Każda linia rozwija ten sam pomysł: dobrze zaprojektowana technologia powinna ułatwiać prowadzenie, a nie odwracać od niego uwagę.', end: 'Od projektu do drogi', ending: 'Proces rozwoju łączy prace konstrukcyjne z próbami podwozia, ergonomii i układu napędowego. Sieć obsługi AsperGenerator zapewnia zaplecze serwisowe i dostęp do części dla całej gamy pojazdów.' },
    ciezarowe: { label: '02 / TRANSPORT', title: 'Samochody ciężarowe', slogan: 'Ciężka praca. Mocne zaplecze.', heading: 'Transport bez zbędnych kompromisów.', intro: 'Gdy zadanie wymaga przewiezienia więcej, liczy się solidna konstrukcja i łatwa obsługa. Dział pojazdów użytkowych AsperGenerator dostarcza rozwiązania dla logistyki, budownictwa i transportu specjalistycznego.', stats: [['Cargo', 'Transport regionalny'], ['Haul', 'Trasy dalekobieżne'], ['Works', 'Zadania terenowe']], second: 'Narzędzie dopasowane do zadania.', body: 'Modułowa konstrukcja podwozia umożliwia przygotowanie pojazdu pod różne zabudowy. Kabiny projektujemy z uwzględnieniem widoczności i codziennej pracy kierowcy, a punkty obsługowe pozostają łatwo dostępne.', end: 'Zaplecze dla całej floty', ending: 'Długoterminowa eksploatacja zaczyna się od planu. Nasz dział wsparcia pomaga dobrać harmonogram obsługi, konfigurację pojazdów i zapas części do charakteru pracy floty.' },
    transformator: { label: '03 / ENERGETYKA', title: 'Komora Transformatora™', slogan: 'W samym centrum energii.', heading: 'Moc pod pełną kontrolą.', intro: 'Komora Transformatora™ to zintegrowane rozwiązanie dla infrastruktury energetycznej AsperGenerator. W jednej przestrzeni łączy układ transformacji, chłodzenie i monitoring — tworząc techniczne serce zakładów, które nie mogą stać w miejscu.', stats: [['Modułowa', 'Architektura systemu'], ['24 / 7', 'Monitoring instalacji'], ['AG Core', 'System zarządzania']], second: 'Zaprojektowana jako całość.', body: 'Każdy element komory jest częścią wspólnego systemu. Rozmieszczenie urządzeń uwzględnia przepływ powietrza, dostęp serwisowy i możliwość rozbudowy. Osłony oddzielają strefy robocze, a centralny panel zbiera informacje o pracy instalacji.', end: 'Energia na kolejne etapy', ending: 'Komora może rozwijać się razem z zakładem. Modułowy układ pozwala planować kolejne sekcje bez przebudowy całej infrastruktury. Zespół AsperGenerator wspiera dobór konfiguracji, integrację z obiektem oraz obsługę podczas eksploatacji.' },
    przemysl: { label: '04 / PRODUKCJA', title: 'Rozwiązania przemysłowe', slogan: 'Od koncepcji do działającego zakładu.', heading: 'System, w którym wszystko współpracuje.', intro: 'Tworzymy zaplecze dla produkcji: stanowiska robocze, instalacje pomocnicze i rozwiązania automatyki. Punktem wyjścia jest zawsze proces — jego wymagania, ograniczenia i ludzie, którzy przy nim pracują.', stats: [['Projekt', 'Analiza potrzeb'], ['Integracja', 'Połączenie systemów'], ['Rozwój', 'Możliwość rozbudowy']], second: 'Inżynieria całego procesu.', body: 'Łączymy konstrukcję mechaniczną z zasilaniem i sterowaniem. Spójny projekt ułatwia obsługę oraz pomaga zachować porządek w dokumentacji. Poszczególne moduły można dostosować do układu hali i kolejnych etapów inwestycji.', end: 'Przestrzeń na przyszłe zadania', ending: 'Wraz ze zmianą skali produkcji zmieniają się potrzeby zakładu. Projektujemy rozwiązania z myślą o dostępie do urządzeń i późniejszej rozbudowie, aby kolejne zmiany miały solidny punkt wyjścia.' },
    serwis: { label: '05 / WSPARCIE', title: 'Serwis i części', slogan: 'Gotowość zaczyna się od dobrego serwisu.', heading: 'Dbamy o ciąg dalszy.', intro: 'Oddanie maszyny do pracy to początek jej historii. Dział wsparcia AsperGenerator zajmuje się diagnostyką, przeglądami i doborem części do pojazdów oraz instalacji naszej grupy.', stats: [['Diagnostyka', 'Rozpoznanie problemu'], ['Przeglądy', 'Planowa obsługa'], ['Części', 'Dobór podzespołów']], second: 'Wiedza o każdym podzespole.', body: 'Dobra obsługa opiera się na dokumentacji i znajomości konstrukcji. Zespoły techniczne pracują na wspólnych standardach, a historia przeglądów pomaga planować kolejne czynności serwisowe.', end: 'Przygotuj zgłoszenie', ending: 'Aby usprawnić obsługę w ramach roleplayu, przygotuj model urządzenia, jego numer seryjny oraz opis objawów. Z tymi informacjami zgłoś się do przedstawiciela firmy w kanale kontaktowym swojego serwera.' },
    dzwigi: { label: '06 / CIĘŻKA TECHNIKA', title: 'Dźwigi', slogan: 'Nowa perspektywa na ciężkie zadania.', heading: 'Precyzja na wysokości.', intro: 'Dział techniki dźwigowej AsperGenerator wspiera budownictwo i przemysł. Projektujemy rozwiązania do podnoszenia i pozycjonowania ładunków z uwzględnieniem warunków terenu, zasięgu pracy i organizacji placu budowy.', stats: [['Mobilne', 'Praca w terenie'], ['Wieżowe', 'Obsługa budowy'], ['Przemysłowe', 'Transport w zakładzie']], second: 'Siła potrzebuje precyzji.', body: 'Stabilna konstrukcja, czytelne sterowanie i dobra widoczność tworzą podstawę pracy operatora. Różne konfiguracje pozwalają dopasować sprzęt do charakteru inwestycji i dostępnego miejsca.', end: 'Planowanie przed podnoszeniem', ending: 'Każda realizacja wymaga właściwego przygotowania. Zespół techniczny pomaga określić konfigurację maszyny i zaplecze serwisowe odpowiednie do zadania w świecie gry.' },
    eula: { label: 'INFORMACJE / ROLEPLAY', title: 'EULA i informacje', slogan: 'Fikcyjny świat. Jasne zasady.', heading: 'O tym projekcie.', intro: 'AsperGenerator to fikcyjna firma stworzona na potrzeby roleplayu. Opisy produktów, systemów i usług są elementem świata gry. Ta strona nie stanowi rzeczywistej oferty handlowej ani dokumentacji technicznej.', stats: [['RP', 'Projekt fabularny'], ['Demo', 'Przykładowe treści'], ['Bez kont', 'Brak rejestracji']], second: 'Korzystanie ze strony', body: 'Materiały służą budowaniu historii i prezentacji firmy w grze. Parametry oraz nazwy rozwiązań mają charakter fabularny i nie powinny być wykorzystywane do projektowania lub obsługi rzeczywistych urządzeń.', end: 'Prywatność i materiały', ending: 'Strona nie zawiera formularzy, analityki ani własnych plików cookie. Krój pisma jest pobierany z Google Fonts, a hosting może prowadzić własne logi techniczne. Ilustracja zakładu została wygenerowana na potrzeby projektu. To przykładowa informacja do dostosowania przez właściciela serwera, nie gotowa umowa licencyjna.' }
};
const home = document.getElementById('home'), detail = document.getElementById('detail'), railInner = document.querySelector('.rail-inner');
let lastTrigger = null;
function render() {
    const key = decodeURIComponent(location.hash.slice(1)), data = divisions[key];
    if (!data) { document.body.classList.remove('open'); home.inert = false; home.removeAttribute('aria-hidden'); detail.inert = true; detail.setAttribute('aria-hidden', 'true'); railInner.inert = false; document.title = 'AsperGenerator — Inżynieria jutra'; if (lastTrigger) { lastTrigger.focus({ preventScroll: true }); lastTrigger = null; } return; }
    document.getElementById('detail-label').textContent = data.label;
    document.getElementById('detail-title').textContent = data.title;
    document.getElementById('detail-body').innerHTML = `<section class="detail-banner"><p>${data.slogan}</p></section><div class="article-content"><div class="article-intro"><h2>${data.heading}</h2><p>${data.intro}</p></div><h2>${data.second}</h2><p>${data.body}</p><h2>${data.end}</h2><p>${data.ending}</p></div>`;
    detail.scrollTop = 0; detail.inert = false; detail.setAttribute('aria-hidden', 'false'); home.inert = true; home.setAttribute('aria-hidden', 'true'); railInner.inert = true; document.body.classList.add('open'); document.title = data.title + ' — AsperGenerator'; document.getElementById('detail-title').focus({ preventScroll: true });
}
document.querySelectorAll('[data-open]').forEach(button => button.addEventListener('click', () => { lastTrigger = button; location.hash = button.dataset.open }));
document.querySelectorAll('nav a,.eula').forEach(link => link.addEventListener('click', () => { lastTrigger = link }));
function closeDetail() { location.hash = ''; }
// Przyciski powrotu są opcjonalne — usunięcie jednego nie zatrzyma nawigacji.
document.querySelectorAll('#back, #bottom-back').forEach(button => {
    button.addEventListener('click', closeDetail);
});
document.addEventListener('keydown', e => { if (e.key === 'Escape' && document.body.classList.contains('open')) closeDetail() });
window.addEventListener('hashchange', render); render();
